name: treering
description: A minimalist mood tracking app.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  image_picker: ^1.1.2
  fl_chart: ^1.0.0
  flutter_plugin_android_lifecycle: ^2.0.6
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
  assets:
    - assets/images/start_bg.jpg